version: '3.4'

services:
  jg.flix.catalog.db:
    container_name: catelogdb
    hostname: catalogdb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
networks:
  default:
    name: service_catalog  